### ISSUE TITLE
Mod importing error 

### ISSUE THREAD

**Issue by small2998** [simon50keda/ConverterPIXWrapper#12]
Hello. Whenever I'm importing a car mod in blender using converter pix wrapper it gives me an error in the picture. It was working fine before upgrade 1.50. I'm using blender v2.93. Anyone who has an idea why is thi happening please help. Thanks in advance.
![20240520_225123](https://github.com/simon50keda/ConverterPIXWrapper/assets/167852286/bb4272a9-b2a5-44f3-a0a6-c53074065b6c)

**Comment by AmirMahdaviAM** [comment]
Which car? Write address
Update blender to 3.3 or 3.6 lts version
And update blender tools to lastest version

**Comment by small2998** [comment]
It's a Volkswagen Polo Rline 2019 by trzpro mods. I will try to upgrade to the versions you mentioned and see.

**Comment by small2998** [comment]
> Which car? Write address Update blender to 3.3 or 3.6 lts version And update blender tools to lastest version

The issue still persists. But I think is with that car mod because I tried importing another car mod (hilux) and that shader error didn't show up. Anyways, thanks alot.

**Comment by AmirMahdaviAM** [comment]
Yeah, i guess. So mark issue as completed please
