### ISSUE TITLE
Addon not installing

### ISSUE THREAD

**Issue by SavantSusi** [simon50keda/ConverterPIXWrapper#3]
I'm in 3.4.1 and I'm installing the addon from the zip file. It says modules installed but the addon doesn't show up in the list and I see no option to import the stuff.

**Comment by simon50keda** [comment]
Hi,
thx for the report. Gonna take a look.

**Comment by simon50keda** [comment]
Please paste console output of the blender. I tried installing it on 3.4.1 and it worked for me without an issue :/

**Comment by SavantSusi** [comment]
Now it works, huh. Did nothing yesterday.
