### ISSUE TITLE
Can't open files

### ISSUE THREAD

**Issue by DarkOleks** [simon50keda/ConverterPIXWrapper#6]
Hi! So I downloaded this add-on using the zip file, then tried opening base.scs, but i just get a blank screen. I'm running it on MacOS, so maybe that is the issue, but if you can help, I will be very thankful

<img width="1440" alt="Screenshot 2023-07-21 at 17 35 23" src="https://github.com/simon50keda/ConverterPIXWrapper/assets/67630432/731f2c4b-db99-444d-87c4-0052801f0a20">

**Comment by DarkOleks** [comment]
Maybe I'm not patient enough, and I need to wait more to load the file, but in some video tutorials everything looked instant

**Comment by simon50keda** [comment]
Nope this means you don't have latest binaries of ConverterPIX.

**Comment by DarkOleks** [comment]
Where and how can I download them?

**Comment by simon50keda** [comment]
So it turns out that wrapper had to be adjusted too. Thus we updated it, please download & install latest version of ConverterPIXWrapper: https://github.com/simon50keda/ConverterPIXWrapper/releases/tag/v2.1
