### ISSUE TITLE
Здравствуйте, подскажите почему при открытии scs файла ничего нету ?

### ISSUE THREAD

**Issue by 003Nikita003** [simon50keda/ConverterPIXWrapper#8]
![Снимок](https://github.com/simon50keda/ConverterPIXWrapper/assets/161368255/68f2a513-f9e7-4258-b275-cffa3593d4c3)

**Comment by Riipperino** [comment]
locked file gives those results

**Comment by simon50keda** [comment]
As mentioned, "bad" archives.
